-- Step 11: private in-app notifications and database-scheduled reminders.
-- pg_cron runs only SQL in the local database; no email or external service is used.

create extension if not exists pg_cron;

create table public.notification_preferences (
  member_id uuid not null references public.member_profiles (id) on delete restrict,
  category text not null,
  enabled boolean not null,
  updated_at timestamptz not null default pg_catalog.clock_timestamp(),
  primary key (member_id, category),
  constraint notification_preferences_category_check check (
    category in (
      'announcement', 'new_poll', 'poll_closing', 'attendance_open', 'event_activity'
    )
  )
);

create table public.notifications (
  id uuid primary key default pg_catalog.gen_random_uuid(),
  recipient_id uuid not null references public.member_profiles (id) on delete restrict,
  category text not null,
  title text not null,
  body text not null,
  source_type text not null,
  source_id uuid,
  event_id uuid references public.events (id) on delete restrict,
  dedupe_key text not null,
  created_at timestamptz not null default pg_catalog.clock_timestamp(),
  read_at timestamptz,
  constraint notifications_category_check check (
    category in (
      'announcement', 'new_poll', 'poll_closing', 'attendance_open',
      'dues_reminder', 'event_activity', 'officer_money', 'officer_member', 'officer_event'
    )
  ),
  constraint notifications_source_type_check check (
    source_type in ('announcement', 'poll', 'attendance', 'dues', 'event', 'audit')
  ),
  constraint notifications_title_check check (
    pg_catalog.char_length(title) between 1 and 120 and title !~ '[[:cntrl:]]'
  ),
  constraint notifications_body_check check (
    pg_catalog.char_length(body) between 1 and 300
    and pg_catalog.translate(body, E'\n\r\t', '') !~ '[[:cntrl:]]'
  ),
  constraint notifications_dedupe_key_check check (
    dedupe_key ~ '^[a-z][a-z0-9:_-]{1,127}$'
  ),
  constraint notifications_read_after_create_check check (
    read_at is null or read_at >= created_at
  ),
  constraint notifications_recipient_dedupe_key unique (recipient_id, dedupe_key)
);

create index notifications_recipient_history_idx
  on public.notifications (recipient_id, created_at desc, id desc);
create index notifications_event_id_idx
  on public.notifications (event_id)
  where event_id is not null;

alter table public.notification_preferences enable row level security;
alter table public.notification_preferences force row level security;
alter table public.notifications enable row level security;
alter table public.notifications force row level security;

create policy notification_preferences_select_self
  on public.notification_preferences for select to authenticated
  using (
    member_id = (select auth.uid())
    and (select private.is_active_club_member())
  );

create policy notifications_select_recipient
  on public.notifications for select to authenticated
  using (
    recipient_id = (select auth.uid())
    and (select private.is_active_club_member())
  );

revoke all on table public.notification_preferences
  from public, anon, authenticated, service_role;
revoke all on table public.notifications
  from public, anon, authenticated, service_role;
grant select on table public.notification_preferences to authenticated;
grant select on table public.notifications to authenticated;

create table private.notification_job_runs (
  job_key text primary key,
  completed_at timestamptz not null default pg_catalog.clock_timestamp(),
  constraint notification_job_runs_key_check check (
    job_key ~ '^dues:[0-9]{4}-[0-9]{2}$'
  )
);
revoke all on table private.notification_job_runs
  from public, anon, authenticated, service_role;

create or replace function private.guard_notification_write()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if tg_op = 'DELETE' then
    raise exception using errcode = '42501', message = 'Notifications are retained.';
  elsif tg_op = 'INSERT' then
    if pg_catalog.current_setting('app.notification_insert_write', true) is distinct from 'on' then
      raise exception using errcode = '42501', message = 'Notifications are generated by trusted database logic.';
    end if;
    return new;
  end if;

  if pg_catalog.current_setting('app.notification_read_write', true) is distinct from 'on'
    or old.read_at is not null or new.read_at is null
    or new.id is distinct from old.id
    or new.recipient_id is distinct from old.recipient_id
    or new.category is distinct from old.category
    or new.title is distinct from old.title
    or new.body is distinct from old.body
    or new.source_type is distinct from old.source_type
    or new.source_id is distinct from old.source_id
    or new.event_id is distinct from old.event_id
    or new.dedupe_key is distinct from old.dedupe_key
    or new.created_at is distinct from old.created_at then
    raise exception using errcode = '42501', message = 'Only an unread notification can be marked read.';
  end if;
  return new;
end;
$function$;

create trigger notifications_write_guard
before insert or update or delete on public.notifications
for each row execute function private.guard_notification_write();

create or replace function private.fanout_member_notification(
  p_category text,
  p_dedupe_key text,
  p_source_type text,
  p_source_id uuid,
  p_event_id uuid,
  p_title text,
  p_body text,
  p_actor_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if p_category not in (
       'announcement', 'new_poll', 'poll_closing', 'attendance_open', 'event_activity'
     )
     or p_source_type not in ('announcement', 'poll', 'attendance', 'event')
     or p_dedupe_key is null or p_title is null or p_body is null then
    raise exception using errcode = '23514', message = 'Notification request is invalid.';
  end if;

  perform pg_catalog.set_config('app.notification_insert_write', 'on', true);
  insert into public.notifications (
    recipient_id, category, title, body, source_type, source_id,
    event_id, dedupe_key
  )
  select
    profile.id, p_category, p_title, p_body, p_source_type,
    p_source_id, p_event_id, p_dedupe_key
  from public.member_profiles as profile
  left join public.notification_preferences as preference
    on preference.member_id = profile.id
   and preference.category = p_category
  where profile.status = 'active'
    and profile.id is distinct from p_actor_id
    and coalesce(preference.enabled, true)
  on conflict (recipient_id, dedupe_key) do nothing;
  perform pg_catalog.set_config('app.notification_insert_write', 'off', true);
end;
$function$;

create or replace function private.fanout_officer_notification(
  p_category text,
  p_dedupe_key text,
  p_source_type text,
  p_source_id uuid,
  p_event_id uuid,
  p_title text,
  p_body text,
  p_actor_id uuid default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if p_category not in ('officer_money', 'officer_member', 'officer_event')
     or p_source_type not in ('audit', 'event')
     or p_dedupe_key is null or p_title is null or p_body is null then
    raise exception using errcode = '23514', message = 'Notification request is invalid.';
  end if;

  perform pg_catalog.set_config('app.notification_insert_write', 'on', true);
  insert into public.notifications (
    recipient_id, category, title, body, source_type, source_id,
    event_id, dedupe_key
  )
  select distinct
    profile.id, p_category, p_title, p_body, p_source_type,
    p_source_id, p_event_id, p_dedupe_key
  from public.member_profiles as profile
  where profile.status = 'active'
    and profile.id is distinct from p_actor_id
    and (
      exists (
        select 1
        from public.member_role_assignments as club_role
        where club_role.member_id = profile.id
          and club_role.role in ('executive', 'admin', 'backup_admin')
          and club_role.revoked_at is null
      )
      or (
        p_event_id is not null
        and exists (
          select 1
          from public.event_role_assignments as event_role
          where event_role.member_id = profile.id
            and event_role.event_id = p_event_id
            and event_role.role in ('lead', 'assistant')
            and event_role.revoked_at is null
        )
      )
    )
  on conflict (recipient_id, dedupe_key) do nothing;
  perform pg_catalog.set_config('app.notification_insert_write', 'off', true);
end;
$function$;

create or replace function private.notify_from_audit_log()
returns trigger
language plpgsql
security definer
set search_path = ''
as $function$
begin
  if new.action = 'announcement.created' then
      perform private.fanout_member_notification(
        'announcement', 'announcement:' || new.entity_id::text,
        'announcement', new.entity_id, new.event_id,
        'New announcement', 'A new club announcement is available.', new.actor_id
      );
    elsif new.action = 'poll.created' then
      perform private.fanout_member_notification(
        'new_poll', 'poll:' || new.entity_id::text,
        'poll', new.entity_id, new.event_id,
        'New poll', 'A new club poll is available.', new.actor_id
      );
    elsif new.action = 'attendance.session_opened' then
      perform private.fanout_member_notification(
        'attendance_open', 'attendance-open:' || new.entity_id::text,
        'attendance', new.entity_id, coalesce(new.event_id, new.entity_id),
        'Attendance is open', 'Check in for the event while the session is open.', new.actor_id
      );
    elsif new.action in (
      'event_created', 'event_details_updated', 'event_completed',
      'event_cancelled', 'event_reopened', 'event_archived'
    ) then
      perform private.fanout_member_notification(
        'event_activity', 'event-activity:' || new.id::text,
        'event', coalesce(new.event_id, new.entity_id),
        coalesce(new.event_id, new.entity_id),
        'Event update', 'Club event information has changed. Open events to review it.', new.actor_id
      );
      perform private.fanout_officer_notification(
        'officer_event', 'officer-event:' || new.id::text,
        'audit', new.id, coalesce(new.event_id, new.entity_id),
        'An event record changed', 'Review the event history and current event details.', new.actor_id
      );
    elsif new.action in (
      'member_approved', 'member_deactivated', 'member_reactivated',
      'club_role_granted', 'club_role_revoked'
    ) then
      perform private.fanout_officer_notification(
        'officer_member', 'officer-member:' || new.id::text,
        'audit', new.id, null,
        'A membership record changed', 'Review member administration and its audit history.', new.actor_id
      );
    elsif new.action like 'dues_%'
       or new.action like 'club_finance_%'
       or new.action like 'event_finance_%'
       or new.action like 'event_ticket_%'
       or new.action like 'event_ledger_%'
       or new.action like 'event_budget_%'
       or new.action in ('finance_category_created', 'finance_category_retired') then
      perform private.fanout_officer_notification(
        'officer_money', 'officer-money:' || new.id::text,
        'audit', new.id, new.event_id,
        'A financial record changed', 'Review the relevant private or event finance records.', new.actor_id
      );
  end if;
  return new;
end;
$function$;

create trigger audit_log_notification_fanout
after insert on public.audit_log
for each row execute function private.notify_from_audit_log();

create or replace function private.set_notification_preference(
  p_category text,
  p_enabled boolean
)
returns void
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_actor_id uuid := (select auth.uid());
  v_previous boolean;
  v_found boolean;
begin
  if v_actor_id is null or not (select private.is_active_club_member()) then
    raise exception using errcode = '42501', message = 'An active member account is required.';
  end if;
  if p_category not in ('announcement', 'new_poll', 'poll_closing', 'attendance_open', 'event_activity')
     or p_enabled is null then
    raise exception using errcode = '23514', message = 'Notification preference is invalid.';
  end if;

  select preference.enabled into v_previous
  from public.notification_preferences as preference
  where preference.member_id = v_actor_id and preference.category = p_category
  for update;
  v_found := found;
  if v_found and v_previous = p_enabled then
    return;
  end if;

  insert into public.notification_preferences (member_id, category, enabled)
  values (v_actor_id, p_category, p_enabled)
  on conflict (member_id, category) do update
    set enabled = excluded.enabled, updated_at = pg_catalog.clock_timestamp();

  insert into public.audit_log (
    actor_id, action, entity_type, entity_id, target_member_id,
    before_data, after_data, reason
  ) values (
    v_actor_id, 'notification.preference_changed', 'notification_preference',
    v_actor_id, v_actor_id,
    case when v_found then pg_catalog.jsonb_build_object(
      'category', p_category, 'enabled', v_previous
    ) else null end,
    pg_catalog.jsonb_build_object('category', p_category, 'enabled', p_enabled),
    'Member changed an in-app notification preference.'
  );
end;
$function$;

create or replace function private.mark_notification_read(p_notification_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_actor_id uuid := (select auth.uid());
begin
  if v_actor_id is null or not (select private.is_active_club_member()) then
    raise exception using errcode = '42501', message = 'An active member account is required.';
  end if;
  if p_notification_id is null then
    raise exception using errcode = '23514', message = 'Notification identifier is invalid.';
  end if;

  perform pg_catalog.set_config('app.notification_read_write', 'on', true);
  update public.notifications
  set read_at = pg_catalog.clock_timestamp()
  where id = p_notification_id
    and recipient_id = v_actor_id
    and read_at is null;
  perform pg_catalog.set_config('app.notification_read_write', 'off', true);
end;
$function$;

create or replace function public.set_notification_preference(
  p_category text,
  p_enabled boolean
)
returns void
language sql
security invoker
set search_path = ''
as $function$
  select private.set_notification_preference(p_category, p_enabled);
$function$;

create or replace function public.mark_notification_read(p_notification_id uuid)
returns void
language sql
security invoker
set search_path = ''
as $function$
  select private.mark_notification_read(p_notification_id);
$function$;

create or replace function private.queue_dues_notifications(p_month date)
returns integer
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_month date := pg_catalog.date_trunc('month', p_month)::date;
  v_job_key text;
  v_inserted_key text;
  v_count integer;
begin
  if p_month is null or p_month <> v_month
     or v_month > pg_catalog.date_trunc(
       'month', pg_catalog.clock_timestamp() at time zone 'Africa/Lagos'
     )::date then
    raise exception using errcode = '23514', message = 'Dues reminder period is invalid.';
  end if;
  if not exists (
    select 1 from public.dues_rates as rate where rate.effective_month <= v_month
  ) then
    raise exception using errcode = '23514', message = 'The dues rate is not configured.';
  end if;

  v_job_key := 'dues:' || pg_catalog.to_char(v_month, 'YYYY-MM');
  insert into private.notification_job_runs (job_key)
  values (v_job_key)
  on conflict (job_key) do nothing
  returning job_key into v_inserted_key;
  if v_inserted_key is null then
    return 0;
  end if;

  perform pg_catalog.set_config('app.notification_insert_write', 'on', true);
  insert into public.notifications (
    recipient_id, category, title, body, source_type, dedupe_key
  )
  select profile.id, 'dues_reminder', 'Monthly dues reminder',
    'Your dues reminder is ready. Open your private dues page to review your status.',
    'dues', 'dues:' || pg_catalog.to_char(v_month, 'YYYY-MM')
  from public.member_profiles as profile
  join public.dues_membership_periods as period
    on period.member_id = profile.id
   and period.starts_month <= v_month
   and (period.ends_before_month is null or v_month < period.ends_before_month)
  where profile.status = 'active'
    and not exists (
      select 1 from public.dues_month_dispositions as disposition
      where disposition.member_id = profile.id
        and disposition.covered_month = v_month
        and disposition.is_current
    )
  on conflict (recipient_id, dedupe_key) do nothing;
  get diagnostics v_count = row_count;
  perform pg_catalog.set_config('app.notification_insert_write', 'off', true);
  return v_count;
end;
$function$;

create or replace function private.queue_poll_closing_notifications(p_as_of timestamptz)
returns integer
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_poll record;
  v_count integer := 0;
begin
  if p_as_of is null then
    raise exception using errcode = '23514', message = 'Notification time is invalid.';
  end if;
  for v_poll in
    select poll.id, poll.event_id
    from public.announcement_polls as poll
    where poll.closes_at > p_as_of
      and poll.created_at + ((poll.closes_at - poll.created_at) * 0.75) <= p_as_of
    order by poll.closes_at, poll.id
    limit 250
  loop
    perform private.fanout_member_notification(
      'poll_closing', 'poll-closing:' || v_poll.id::text,
      'poll', v_poll.id, v_poll.event_id,
      'Poll closing soon', 'A club poll is closing soon. Open announcements to review it.', null
    );
    v_count := v_count + 1;
  end loop;
  return v_count;
end;
$function$;

create or replace function private.generate_scheduled_notifications()
returns void
language plpgsql
security definer
set search_path = ''
as $function$
declare
  v_local_now timestamp without time zone :=
    pg_catalog.clock_timestamp() at time zone 'Africa/Lagos';
begin
  if pg_catalog.date_part('day', v_local_now)::integer = 1 then
    perform private.queue_dues_notifications(
      pg_catalog.date_trunc('month', v_local_now)::date
    );
  end if;
  perform private.queue_poll_closing_notifications(pg_catalog.clock_timestamp());
end;
$function$;

revoke all on function private.guard_notification_write() from public, anon, authenticated, service_role;
revoke all on function private.fanout_member_notification(text, text, text, uuid, uuid, text, text, uuid) from public, anon, authenticated, service_role;
revoke all on function private.fanout_officer_notification(text, text, text, uuid, uuid, text, text, uuid) from public, anon, authenticated, service_role;
revoke all on function private.notify_from_audit_log() from public, anon, authenticated, service_role;
revoke all on function private.set_notification_preference(text, boolean) from public, anon, authenticated, service_role;
revoke all on function private.mark_notification_read(uuid) from public, anon, authenticated, service_role;
revoke all on function private.queue_dues_notifications(date) from public, anon, authenticated, service_role;
revoke all on function private.queue_poll_closing_notifications(timestamptz) from public, anon, authenticated, service_role;
revoke all on function private.generate_scheduled_notifications() from public, anon, authenticated, service_role;
grant execute on function private.set_notification_preference(text, boolean) to authenticated;
grant execute on function private.mark_notification_read(uuid) to authenticated;

revoke all on function public.set_notification_preference(text, boolean) from public, anon, authenticated, service_role;
revoke all on function public.mark_notification_read(uuid) from public, anon, authenticated, service_role;
grant execute on function public.set_notification_preference(text, boolean) to authenticated;
grant execute on function public.mark_notification_read(uuid) to authenticated;

-- Supabase Cron executes in PostgreSQL (no service-role key or external secret).
-- Use its scheduling API; Supabase no longer permits direct cron.job writes.
select cron.unschedule(jobid)
from cron.job
where jobname = 'carpenters-in-app-notifications';

select cron.schedule(
  'carpenters-in-app-notifications',
  '* * * * *',
  'select private.generate_scheduled_notifications();'
);
